### ISSUE TITLE
add an option for exporting straight to pdf?

### ISSUE THREAD

**Issue by samuelmehr** [lowercasename/docdown#12]
it would be really cool to use DocDown to go straight from markdown with Zotero refs to a clean pdf — is that in the works?

**Comment by lowercasename** [comment]
I'm going to look into choose-your-own export formats in a future release, thank you for the suggestion!

**Comment by kenanmike** [comment]
I came to give this suggestion then found it already here!

**Comment by lowercasename** [comment]
I've looked into this! The [newest release](https://github.com/lowercasename/docdown/releases/tag/v0.6.0) allows for exporting into Word, ODT, HTML and EPUB, but PDF is much more complicated because in Pandoc it's designed to work from LaTeX, not Markdown, and we can't make use of the Word style references file during PDF export.

I recommend you just use Word's export to PDF function, which is unfortunately... quite good.
